version: '3.9'

services:
  web:
    build: ./summarizer_web
#    command: docker run -d -p 5000:5000 summarizer-web
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      SECRET_KEY: "${SECRET_KEY}"
#      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
